version: '3'
services:
  # Kontener MySQL
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: paliwo
      MYSQL_USER: haef
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  # Kontener Apache i PHP
  webserver:
    image: php:7.4-apache
    container_name: webserver-container
    volumes:
      - ./php_code:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - mysql

  # Kontener phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    depends_on:
      - mysql


